name: Push "Hello World"

# Trigger this workflow on any push to the main branch
on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Create or update a file with "Hello World"
    - name: Add "Hello World" to file
      run: echo "Hello World" >> hello_world.txt

    # Commit the change and push it back to the main branch
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add hello_world.txt
        git commit -m "Add Hello World"
        git push
      env:
        # This token is automatically provided by GitHub Actions
        # No need to configure it manually
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
